<a href="https://colab.research.google.com/github/Olveir/Monitoria_CD/blob/main/Resposta_Exercicios_Aula03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importando o DataSet

In [ ]:
import pandas as pd
import seaborn as sns

In [ ]:
# Carregar o DataFrame Titanic
df_titanic = sns.load_dataset('titanic')

> Como visto na aula anterior, uma das etapas mais importantes do **Pré-Processamento** é o que chamamos de **Imputação.**

> Nela, tratamos valores vazios e removemos dados indesejados.

- Agora, a partir do DataSet titânic, faça a imputação dos a dados a partir das exigências!

## Imputação

Decisões em cima dos dados vazios:
- **Média**
  - Desvio Padrão
- **Moda**
- **Mediana**
- **Remoção Total:** Remoção de todos os valores faltantes, importante para colunas inuteis.

Funções usadas:
- `.fillna()` : preenche os valores vazios com algum valor.
    - `.fillna(df['exemplo'].mean(), inplace=True)`
- `.replace()` : substitui um valor por outro.
    - `df['floor'].replace('-', np.nan)`
- `.dropna()` : remove linhas que contem valores vazios.
    - `dropna(subset=['exemplo'], inplace=True)`
- `drop()` : remove uma coluna.
    - `.drop(columns=['exemplo_1', 'exemplo_2', ..., 'exemplo_n'], inplace=True)`

obs: o uso do `inplace=True`, faz com que os dados alterados, sejam alterados no DataFrame príncipal.

In [ ]:
df_titanic.head()
#df_titanic.dtypes

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
# Imputação da coluna 'idade' com a mediana
df_titanic['age'] = df_titanic['age'].fillna(df_titanic['age'].median())


# Decisão de remover valores faltantes na coluna 'Embark_Town'
df_titanic.dropna(subset=['embark_town'], inplace=True)

# Removor colunas 'Alive', 'Class', 'embarked', 'deck', 'alive',
# 'adult_male' e 'embark_town'
df_titanic.drop(columns=['alive', 'class', 'embarked', 'deck','adult_male','embark_town'], inplace=True)

- A decisão de remover estas colunas, se da pelas redundancias delas.

Verificação

In [ ]:
# Verifique novamente os valores ausentes
df_titanic.isnull().sum()

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
who         0
alone       0
dtype: int64

In [ ]:
# Me de o resumo do DataFrame
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   who       889 non-null    object
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB

In [ ]:
# Visualize novamente a cabeça do DataFrame
df_titanic.head()

   survived  pclass     sex   age  sibsp  parch     fare    who  alone
0         0       3    male  22.0      1      0   7.2500    man  False
1         1       1  female  38.0      1      0  71.2833  woman  False
2         1       3  female  26.0      0      0   7.9250  woman   True
3         1       1  female  35.0      1      0  53.1000  woman  False
4         0       3    male  35.0      0      0   8.0500    man   True